name: Scrape API

on:
  workflow_dispatch:
    inputs:
      domain:
        description: domain
        type: string
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.14"]

    steps:
    - uses: actions/checkout@v4
    - name: preparations
      run: |
        mkdir -p out
    - name: run code
      run: |
          npx auto-api-discovery capture ${{ github.event.inputs.domain }}
          npx auto-api-discovery export ./out/scrape.json
    - name: commiting to github
      run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add out/*
          git commit -m "gamebanana"
          git push
