name: Scrape API

on:
  workflow_dispatch:
    inputs:
      domain:
        description: domain
        type: string
        required: true
      max_pages:
        description: max pages
        required: true
        type: number
        default: 100
      timeout:
        description: timeout
        required: true
        type: number
        default: 20000
      delay:
        description: delay
        required: true
        type: number
        default: 1000

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.14"]

    steps:
    - uses: actions/checkout@v4
    - name: run code
      run: |
        git clone https://github.com/mahirozdin/API-Endpoint-Discovery-Tool.git
        cd API-Endpoint-Discovery-Tool
        npm install
        node index.js --domain=${{github.event.inputs.domain}} --maxPages=${{github.event.inputs.max_pages}} --timeout=${{github.event.inputs.timeout}} --delay=${{github.event.inputs.delay}}
    - name: commiting to github
      run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add out/*
          git commit -m "gamebanana"
          git push
