name: Scrape API

on:
  workflow_dispatch:
    inputs:
      domain:
        description: domain
        type: string
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.14"]

    steps:
    - uses: actions/checkout@v4
    - name: preparations
      run: |
        mkdir -p out
    - name: run code
      run: |
        git clone https://github.com/Fruit-Guardians/Api-Finder.git
        cd Api-Finder
        pip install -r requirements.txt
        python main.py -u https://example.com
        python main.py -u https://example.com -o ./out/scrape.json
    - name: commiting to github
      run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add out/*
          git commit -m "gamebanana"
          git push
